export const UPDATE_MINIGAME_LOADING = 'UPDATE_MINIGAME_LOADING';
export const UPDATE_MINIGAME_POKETRIVIA_SUCCESS =
  'UPDATE_MINIGAME_POKETRIVIA_SUCCESS';
export const UPDATE_MINIGAME_POKETRIVIA_ERROR =
  'UPDATE_MINIGAME_POKETRIVIA_ERROR';

export const UPDATE_MINIGAME_POKEGUESS_SUCCESS =
  'UPDATE_MINIGAME_POKEGUESS_SUCCESS';
export const UPDATE_MINIGAME_POKEGUESS_ERROR =
  'UPDATE_MINIGAME_POKEGUESS_ERROR';

export const UPDATE_MINIGAME_POKETYPES_SUCCESS =
  'UPDATE_MINIGAME_POKETYPES_SUCCESS';
export const UPDATE_MINIGAME_POKETYPES_ERROR =
  'UPDATE_MINIGAME_POKETYPES_ERROR';
