export const LIKE_REQUEST_START = 'LIKE_REQUEST_START'

export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS'
export const GET_NOTIFICATIONS_ERROR = 'GET_NOTIFICATIONS_ERROR'

export const LIKE_NOTIFICATION_SUCCESS = 'LIKE_NOTIFICATION_SUCCESS'
export const LIKE_NOTIFICATION_ERROR = 'LIKE_NOTIFICATION_ERROR'
export const DISLIKE_NOTIFICATION_SUCCESS = 'DISLIKE_NOTIFICATION_SUCCESS'
export const DISLIKE_NOTIFICATION_ERROR = 'DISLIKE_NOTIFICATION_ERROR'
