export const GET_NOTIFICATIONS_LOADING = 'GET_NOTIFICATIONS_LOADING';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_ERROR = 'GET_NOTIFICATIONS_ERROR';

export const REACTION_NOTIFICATION_LOADING = 'REACTION_NOTIFICATION_LOADING';
export const LIKE_NOTIFICATION_SUCCESS = 'LIKE_NOTIFICATION_SUCCESS';
export const LIKE_NOTIFICATION_ERROR = 'LIKE_NOTIFICATION_ERROR';
export const DISLIKE_NOTIFICATION_SUCCESS = 'DISLIKE_NOTIFICATION_SUCCESS';
export const DISLIKE_NOTIFICATION_ERROR = 'DISLIKE_NOTIFICATION_ERROR';
