export const API_REQUEST_START = 'API_REQUEST_START';

export const POKEMON_DATA_SUCCESS = 'POKEMONINFO_DATA_SUCCESS';
export const POKEMON_DATA_ERROR = 'POKEMONINFO_DATA_ERROR';
export const POKEMON_EVCHAIN_DATA_ERROR = 'POKEMONINFO_EVOLUTION_DATA_ERROR';
export const POKEMON_ALTERNATEFORM_DATA_ERROR =
  'POKEMONINFO_ALTERNATEFORM_DATA_ERROR';

export const POKELIST_PAGE_DATA_SUCCESS = 'POKELIST_PAGE_DATA_SUCCESS';
export const POKELIST_PAGE_DATA_ERROR = 'POKELIST_PAGE_DATA_ERROR';

export const POKEDEX_DATA_LOADING = 'POKEDEX_DATA_LOADING';
export const POKEDEX_DATA_SUCCESS = 'POKEDEX_DATA_SUCCESS';
export const POKEDEX_DATA_ERROR = 'POKEDEX_DATA_ERROR';

export const POKEMON_REGIONS_GAMES_LOADING = 'POKEMON_REGIONS_GAMES_LOADING';
export const POKEMON_REGIONS_GAMES_SUCCESS = 'POKEMON_REGIONS_GAMES_SUCCESS';
export const POKEMON_REGIONS_GAMES_ERROR = 'POKEMON_REGIONS_GAMES_ERROR';
