export const POKEMONCARDS_DATA_LOADING = 'POKEMONCARDS_DATA_LOADING';
export const POKEMONCARDS_DATA_SUCCESS = 'POKEMONCARDS_DATA_SUCCESS';
export const POKEMONCARDS_DATA_ERROR = 'POKEMONCARDS_DATA_ERROR';

export const POKEMONCARDS_RARITIES_DATA_LOADING =
  'POKEMONCARDS_RARITIES_DATA_LOADING';
export const POKEMONCARDS_RARITIES_DATA_SUCCESS =
  'POKEMONCARDS_RARITIES_DATA_SUCCESS';
export const POKEMONCARDS_RARITIES_DATA_ERROR =
  'POKEMONCARDS_RARITIES_DATA_ERROR';

export const POKEMONCARDS_NEXT_CARDS_DATA_LOADING =
  'POKEMONCARDS_NEXT_CARDS_DATA_LOADING';
export const POKEMONCARDS_NEXT_CARDS_DATA_SUCCESS =
  'POKEMONCARDS_NEXT_CARDS_DATA_SUCCESS';
export const POKEMONCARDS_NEXT_CARDS_DATA_ERROR =
  'POKEMONCARDS_NEXT_CARDS_DATA_ERROR';
