export const POKEMONCARDS_DATA_SUCCESS = 'POKEMONCARDS_DATA_SUCCESS'
export const POKEMONCARDS_DATA_ERROR = 'POKEMONCARDS_DATA_ERROR'

export const POKEMONCARDS_RARITIES_DATA_SUCCESS =
  'POKEMONCARDS_RARITIES_DATA_SUCCESS'
export const POKEMONCARDS_RARITIES_DATA_ERROR =
  'POKEMONCARDS_RARITIES_DATA_ERROR'

export const POKEMONCARDS_SUBTYPES_DATA_SUCCESS =
  'POKEMONCARDS_SUBTYPES_DATA_SUCCESS'
export const POKEMONCARDS_SUBTYPES_DATA_ERROR =
  'POKEMONCARDS_SUBTYPES_DATA_ERROR'
