export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const CHANGE_PROFILE_SUCCESS = 'CHANGE_PROFILE_SUCCESS';
export const CHANGE_PROFILE_ERROR = 'CHANGE_PROFILE_ERROR';

export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';
export const ADD_FAVORITE_ERROR = 'ADD_FAVORITE_ERROR';
export const REMOVE_FAVORITE_SUCCESS = 'REMOVE_FAVORITE_SUCCESS';
export const REMOVE_FAVORITE_ERROR = 'REMOVE_FAVORITE_ERROR';
export const UPDATE_FAVORITE_SUCCESS = 'UPDATE_FAVORITE_SUCCESS';
export const UPDATE_FAVORITE_ERROR = 'UPDATE_FAVORITE_ERROR';

export const ADD_POKEMON_TEAM_SUCCESS = 'ADD_POKEMON_TEAM_SUCCESS';
export const ADD_POKEMON_TEAM_ERROR = 'ADD_POKEMON_TEAM_ERROR';
export const REMOVE_POKEMON_TEAM_SUCCESS = 'REMOVE_POKEMON_TEAM_SUCCESS';
export const REMOVE_POKEMON_TEAM_ERROR = 'REMOVE_POKEMON_TEAM_ERROR';
export const UPDATE_POKEMON_TEAM_SUCCESS = 'UPDATE_POKEMON_TEAM_SUCCESS';
export const UPDATE_POKEMON_TEAM_ERROR = 'UPDATE_POKEMON_TEAM_ERROR';
